### ISSUE TITLE
CI/CD not working

### ISSUE THREAD

**Issue by NestorDevs** [iqans/flutter-ci-github-actions-demo#1]
hello incredible tutorial but I have a problem does not want to compile the app I login with ssh that is a problem? attached img.

![image](https://user-images.githubusercontent.com/36705339/82500087-c94ebb80-9ac0-11ea-8648-0cfc132dd2c4.png)

**Comment by NestorDevs** [comment]
now i have this error... I followed your instructions to the letter
![image](https://user-images.githubusercontent.com/36705339/82566642-38242700-9b4a-11ea-83ed-694d29d7f6a7.png)

**Comment by NestorDevs** [comment]
this is cloning your repository and putting the file in a repository of mine
please help me this is very important to me because I have to work with github action for my boss

![image](https://user-images.githubusercontent.com/36705339/82568910-81c24100-9b4d-11ea-8016-ee0fb1723d02.png)

**Comment by NestorDevs** [comment]
https://github.com/NestorDevs/demo-app.git 
this repository

**Comment by iqan** [comment]
could you please re-run the build please. Looks like some transient issue.
I re-ran the build here. And it worked fine. Please find below screenshot

![image](https://user-images.githubusercontent.com/10431508/82597005-338a5d80-9ba0-11ea-87e5-63c88ee5232e.png)

Please re-open it if the issue persists.
